### ISSUE TITLE
Crash on return from directory picker

### ISSUE THREAD

**Issue by HassanHeydariNasab** [ammarahm-ed/react-native-scoped-storage#1] opened 2021-07-20 15:56 UTC
Hi,
I use `openDocumentTree` method in order to get access to a directory, but after clicking on `use this folder` screen becomes black, and it doesn't return to the app properly.
```
react: 17.0.1,
react-native: 0.64.1,
react-native-scoped-storage: ^1.0.0

buildToolsVersion = "29.0.3"
minSdkVersion = 21
compileSdkVersion = 29
targetSdkVersion = 29
```

Here is the log:
```
07-20 20:10:08.502 27653 27653 E AndroidRuntime: FATAL EXCEPTION: main
07-20 20:10:08.502 27653 27653 E AndroidRuntime: Process: com.test, PID: 27653
07-20 20:10:08.502 27653 27653 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=27867, result=-1, data=Intent { dat=content://com.android.externalstorage.documents/tree/primary: flg=0xc3 }} to activity {com.test/com.test.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.ActivityEventListener.onActivityResult(android.app.Activity, int, int, android.content.Intent)' on a null object reference
07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at android.app.ActivityThread.deliverResults(ActivityThread.java:5057)
07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5098)
07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2105)
07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7700)
07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
07-20 20:10:08.502 27653 27653 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.ActivityEventListener.onActivityResult(android.app.Activity, int, int, android.content.Intent)' on a null object reference
07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:305)
07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:762)
07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:90)
07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:112)
07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:68)
07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at android.app.Activity.dispatchActivityResult(Activity.java:8310)
07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at android.app.ActivityThread.deliverResults(ActivityThread.java:5050)
07-20 20:10:08.502 27653 27653 E AndroidRuntime:        ... 11 more
07-20 20:10:08.504   427   540 I libPowerHal: [perfNotifyAppState] pack:com.test, pid:27653, STATE_DEAD
07-20 20:10:08.508  1006 27738 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
07-20 20:10:08.509  1006  3326 I InputDispatcher: setInputWindows displayId=0 Window{5e4cc58 u0 NavigationBar0} Window{370b3a0 u0 StatusBar} com.google.android.documentsui/com.android.documentsui.picker.PickActivity#1 com.google.android.documentsui/com.android.documentsui.picker.PickActivity#0 Window{57217cb u0 com.android.systemui.ImageWallpaper} 
07-20 20:10:08.517  1006  3325 W ActivityTaskManager:   Force finishing activity com.test/.MainActivity
07-20 20:10:08.527  1006  3326 I InputDispatcher: setInputWindows displayId=0 Window{5e4cc58 u0 NavigationBar0} Window{370b3a0 u0 StatusBar} com.google.android.documentsui/com.android.documentsui.picker.PickActivity#1 com.google.android.documentsui/com.android.documentsui.picker.PickActivity#0 Window{57217cb u0 com.android.systemui.ImageWallpaper} 
07-20 20:10:08.529   442   442 I SurfaceFlinger: operator()(), mtkRenderCntDebug 13, screenshot (com.google.android.documentsui/com.android.documentsui.picker.PickActivity#0)
07-20 20:10:08.529   442   442 I SurfaceFlinger: operator()(), mtkRenderCntDebug 13, screenshot (Dim Layer for - Task=521#0)
07-20 20:10:08.529   442   442 I SurfaceFlinger: operator()(), mtkRenderCntDebug 13, screenshot (com.google.android.documentsui/com.android.documentsui.picker.PickActivity#1)
07-20 20:10:08.536   427   540 I libPowerHal: [perfLockAcq] idx:1 hdl:242 hint:22 pid:427 duration:10000 => ret_hdl:242
07-20 20:10:08.536   427   540 I libPowerHal: [PE] scn:1 hdl:242 hint:22 comm:mtkpower@1.0-se pid:427
```

**Comment by ammarahm-ed** [comment] 2021-07-20 16:00
> Hi,
> I use `openDocumentTree` method in order to get access to a directory, but after clicking on `use this folder` screen becomes black, and it doesn't return to the app properly.
> ```
> react: 17.0.1,
> react-native: 0.64.1,
> react-native-scoped-storage: ^1.0.0
> 
> buildToolsVersion = "29.0.3"
> minSdkVersion = 21
> compileSdkVersion = 29
> targetSdkVersion = 29
> ```
> 
> Here is the log:
> ```
> 07-20 20:10:08.502 27653 27653 E AndroidRuntime: FATAL EXCEPTION: main
> 07-20 20:10:08.502 27653 27653 E AndroidRuntime: Process: com.test, PID: 27653
> 07-20 20:10:08.502 27653 27653 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=27867, result=-1, data=Intent { dat=content://com.android.externalstorage.documents/tree/primary: flg=0xc3 }} to activity {com.test/com.test.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.ActivityEventListener.onActivityResult(android.app.Activity, int, int, android.content.Intent)' on a null object reference
> 07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at android.app.ActivityThread.deliverResults(ActivityThread.java:5057)
> 07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5098)
> 07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
> 07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
> 07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
> 07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2105)
> 07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
> 07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
> 07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7700)
> 07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
> 07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
> 07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
> 07-20 20:10:08.502 27653 27653 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.ActivityEventListener.onActivityResult(android.app.Activity, int, int, android.content.Intent)' on a null object reference
> 07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:305)
> 07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:762)
> 07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:90)
> 07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:112)
> 07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:68)
> 07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at android.app.Activity.dispatchActivityResult(Activity.java:8310)
> 07-20 20:10:08.502 27653 27653 E AndroidRuntime:        at android.app.ActivityThread.deliverResults(ActivityThread.java:5050)
> 07-20 20:10:08.502 27653 27653 E AndroidRuntime:        ... 11 more
> 07-20 20:10:08.504   427   540 I libPowerHal: [perfNotifyAppState] pack:com.test, pid:27653, STATE_DEAD
> 07-20 20:10:08.508  1006 27738 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
> 07-20 20:10:08.509  1006  3326 I InputDispatcher: setInputWindows displayId=0 Window{5e4cc58 u0 NavigationBar0} Window{370b3a0 u0 StatusBar} com.google.android.documentsui/com.android.documentsui.picker.PickActivity#1 com.google.android.documentsui/com.android.documentsui.picker.PickActivity#0 Window{57217cb u0 com.android.systemui.ImageWallpaper} 
> 07-20 20:10:08.517  1006  3325 W ActivityTaskManager:   Force finishing activity com.test/.MainActivity
> 07-20 20:10:08.527  1006  3326 I InputDispatcher: setInputWindows displayId=0 Window{5e4cc58 u0 NavigationBar0} Window{370b3a0 u0 StatusBar} com.google.android.documentsui/com.android.documentsui.picker.PickActivity#1 com.google.android.documentsui/com.android.documentsui.picker.PickActivity#0 Window{57217cb u0 com.android.systemui.ImageWallpaper} 
> 07-20 20:10:08.529   442   442 I SurfaceFlinger: operator()(), mtkRenderCntDebug 13, screenshot (com.google.android.documentsui/com.android.documentsui.picker.PickActivity#0)
> 07-20 20:10:08.529   442   442 I SurfaceFlinger: operator()(), mtkRenderCntDebug 13, screenshot (Dim Layer for - Task=521#0)
> 07-20 20:10:08.529   442   442 I SurfaceFlinger: operator()(), mtkRenderCntDebug 13, screenshot (com.google.android.documentsui/com.android.documentsui.picker.PickActivity#1)
> 07-20 20:10:08.536   427   540 I libPowerHal: [perfLockAcq] idx:1 hdl:242 hint:22 pid:427 duration:10000 => ret_hdl:242
> 07-20 20:10:08.536   427   540 I libPowerHal: [PE] scn:1 hdl:242 hint:22 comm:mtkpower@1.0-se pid:427
> ```

I will try to reproduce and fix it soon.

**Comment by ammarahm-ed** [comment] 2021-07-21 07:29
The issue is fixed now on master. You can test it by installing master branch @HassanHeydariNasab

```
yarn add https://github.com/ammarahm-ed/react-native-scoped-storage.git
```

**Closed** 2021-07-21 07:30 UTC
